### ISSUE TITLE
地点错误

### ISSUE THREAD

**Issue by liux2** [veaba/ncov#7]
美国确诊病例是在华盛顿州，不是华盛顿特区。

**Comment by terryzhuo110** [comment]
具体为西雅图市斯诺霍米什县（Snohomish County）

**Comment by veaba** [comment]
你好，现在地图是根据首都/省会来进行的。

城市级别的定位在开发中。

**Comment by liux2** [comment]
好嘛，如果作者觉得可以，就关闭issue吧
