### ISSUE TITLE
求开一个「大发国难财」的分区

### ISSUE THREAD

**Issue by razertory** [veaba/ncov#9]
参考 https://twitter.com/niepanxinglai/status/1220488769423282176

**Comment by razertory** [comment]
补充 https://twitter.com/yaodi18/status/1220385973499940867

**Comment by veaba** [comment]
虽然很气愤，但这似乎无助于解决什么问题。

**Comment by WenjieZ** [comment]
商品价格由供求关系决定。适当的提价有利于激励供应商。

**Comment by razertory** [comment]
如何看待顺丰快递员截获口罩，在朋友圈自己销售？ https://www.zhihu.com/question/368517742

**Comment by hugetiny** [comment]
其实发生这些并不稀奇，供求关系你说让他自由好还是不自由好?
口罩涨了几毛的还被土匪抓起来的真是可怜。
